export { default as MainLayout } from './MainLayout/MainLayout'
export { default as TitleHeader } from './TitleHeader/TitleHeader'
export { default as Sidebar } from './SideBar/SideBar'
export { default as PostPreview } from './PostPreview/PostPreview'
export { default as VotingHandles } from './VotingHandles/VotingHandles'
export { default as Attachments } from './Attachments/Attachments'
export { default as Reply } from './Reply/Reply'
export { default as CreateForm } from './CreateForm/CreateForm'
export { default as Form } from './Form/Form'
export { default as Modal } from './modal/modal-container'
export { default as AppModals } from './modal/modal-switcher'
// @ts-ignore
export { default as RichTextEditor } from './Editor/Editor'
export { default as ReplyBox } from './ReplyBox/ReplyBox'
export { default as ShowFullThread } from './Thread/Thread'
export { default as Collapse } from './Collapse/Collapse'
export { default as GenerateBrainKey } from './GenerateBrainKey/GenerateBrainKey'
export { default as TagPreview } from './TagPreview/TagPreview'
export { default as TagDropdown } from './TagDropdown/TagDropdown'
export { default as UserNotifications } from './Notifications/Notifications'
export { default as UserNameWithIcon } from './UserNameWithIcon/UserNameWithIcon'
export { default as ComingSoon } from './ComingSoonMessage/ComingSoonMessage'
export { default as InfiniteScrollFeed } from './InfiniteScrollFeed/InfiniteScrollFeed'
export { default as OpeningPost } from './OpeningPost/OpeningPost'
export { default as NotificationItem } from './NotificationItem/NotificationItem'
export { default as SharePost } from './SharePost/SharePost'
export { default as RichTextPreview } from './RichTextPreview/RichTextPreview'
export { default as ReplyHoverElements } from './ReplyHoverElements/ReplyHoverElements'
export { default as ErrorBoundary } from './ErrorBoundary/ErrorBoundary'

export { default as ChooseAccountName } from './modal/sign-up/choose-account-name'
export { default as SectionHeader } from './modal/sign-up/header'
export { default as GenerateKey } from './modal/sign-up/generate-key'
export { default as VerifyKey } from './modal/sign-up/verification'

// modals
export { default as PostWarningCloseModal } from './modal/post-warning-close/post-warning-close'
export { default as SignUpModal } from './modal/sign-up/sign-up-modal'
export { default as WalletUndetectedModal } from './modal/wallet-undetected/wallet-undetected-modal'
export { default as SignInModal } from './modal/sign-in/sign-in-modal'
export { default as SignInModalOptions } from './modal/sign-in/scatter/select-sign-in-option'

export { default as BrainKeySetPassword } from './modal/sign-in/brain-key/set-password'
export { default as SetNewBK } from './modal/sign-in/brain-key/set-new-bk'

export { default as ScatterAskForPassword } from './modal/sign-in/scatter/ask-password'
export { default as SuccessSetup } from './modal/sign-in/success-setup'
